{
 "title": "SRE Working Dashboard",
 "refresh": "5s",
 "panels": [
  {
   "title": "Service UP status",
   "type": "graph",
   "gridPos": { "x": 0, "y": 0, "w": 24, "h": 8 },
   "targets": [
    { "expr": "up" }
   ]
  },
  {
   "title": "Auth Service",
   "type": "graph",
   "gridPos": { "x": 0, "y": 8, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "up{job=\"auth-service\"}"
    }
   ]
  },
  {
   "title": "User Service",
   "type": "graph",
   "gridPos": { "x": 12, "y": 8, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "up{job=\"user-service\"}"
    }
   ]
  }
 ]
}